#ifndef TESTS_MSAFE_CALLFUNCTION_CALLERS_H
#define TESTS_MSAFE_CALLFUNCTION_CALLERS_H

#include "msafe_callfunction_test.h"

#define MSAFE_CALLFUNCTION_TEST_CALLERS(X) \
	X(MSAFE_WEATHER_RAIN) \
	X(MSAFE_WEATHER_SNOW) \
	X(MSAFE_WEATHER_LIGHTNING) \
	X(MSAFE_WEATHER_LIGHTNING_BOLT) \
	X(MSAFE_ROOM_TEXTURE) \
	X(MSAFE_ROOM_WIND) \
	X(MSAFE_ROOM_FOG) \
	X(MSAFE_ROOM_FOG_STATE) \
	X(MSAFE_ROOM_LIGHT_PULSE) \
	X(MSAFE_ROOM_LIGHT_FLICKER) \
	X(MSAFE_ROOM_LIGHT_STROBE) \
	X(MSAFE_ROOM_REFUEL) \
	X(MSAFE_ROOM_CHANGING_FOG) \
	X(MSAFE_ROOM_CHANGING_WIND) \
	X(MSAFE_ROOM_PORTAL_RENDER) \
	X(MSAFE_ROOM_PORTAL_BLOCK) \
	X(MSAFE_ROOM_BREAK_GLASS) \
	X(MSAFE_ROOM_DAMAGE) \
	X(MSAFE_ROOM_REMOVE_ALL_POWERUPS) \
	X(MSAFE_OBJECT_FIRE_WEAPON) \
	X(MSAFE_OBJECT_SETONFIRE) \
	X(MSAFE_OBJECT_SHIELDS) \
	X(MSAFE_OBJECT_ENERGY) \
	X(MSAFE_SHOW_ENABLED_CONTROLS) \
	X(MSAFE_OBJECT_PLAYER_CMASK) \
	X(MSAFE_OBJECT_PLAYER_KEY) \
	X(MSAFE_OBJECT_MOVEMENT_SCALAR) \
	X(MSAFE_OBJECT_RECHARGE_SCALAR) \
	X(MSAFE_OBJECT_WSPEED_SCALAR) \
	X(MSAFE_OBJECT_ARMOR_SCALAR) \
	X(MSAFE_OBJECT_DAMAGE_SCALAR) \
	X(MSAFE_OBJECT_ADD_WEAPON) \
	X(MSAFE_OBJECT_DAMAGE_OBJECT) \
	X(MSAFE_OBJECT_START_SPEW) \
	X(MSAFE_OBJECT_STOP_SPEW) \
	X(MSAFE_OBJECT_NO_RENDER) \
	X(MSAFE_OBJECT_GHOST) \
	X(MSAFE_OBJECT_UNGHOST) \
	X(MSAFE_OBJECT_REMOVE) \
	X(MSAFE_OBJECT_INVULNERABLE) \
	X(MSAFE_OBJECT_CLOAKALLPLAYERS) \
	X(MSAFE_OBJECT_CLOAK) \
	X(MSAFE_OBJECT_LIGHT_DIST) \
	X(MSAFE_OBJECT_LIGHT_COLOR) \
	X(MSAFE_OBJECT_DEFORM) \
	X(MSAFE_OBJECT_SPARKS) \
	X(MSAFE_OBJECT_VIEWER_SHAKE) \
	X(MSAFE_OBJECT_SHAKE_AREA) \
	X(MSAFE_OBJECT_WORLD_POSITION) \
	X(MSAFE_OBJECT_PLAYER_CONTROLAI) \
	X(MSAFE_OBJECT_DESTROY_ROBOTS_EXCEPT) \
	X(MSAFE_SOUND_STREAMING) \
	X(MSAFE_SOUND_2D) \
	X(MSAFE_SOUND_OBJECT) \
	X(MSAFE_SOUND_STOP) \
	X(MSAFE_SOUND_STOP_OBJ) \
	X(MSAFE_SOUND_VOLUME_OBJ) \
	X(MSAFE_MUSIC_REGION) \
	X(MSAFE_MISC_LEVELGOAL) \
	X(MSAFE_MISC_WAYPOINT) \
	X(MSAFE_MISC_ENABLE_SHIP) \
	X(MSAFE_MISC_FILTERED_HUD_MESSAGE) \
	X(MSAFE_MISC_HUD_MESSAGE) \
	X(MSAFE_MISC_GAME_MESSAGE) \
	X(MSAFE_MISC_END_LEVEL) \
	X(MSAFE_MISC_POPUP_CAMERA) \
	X(MSAFE_MISC_CLOSE_POPUP) \
	X(MSAFE_MISC_GUIDEBOT_NAME) \
	X(MSAFE_MISC_START_TIMER) \
	X(MSAFE_MISC_UPDATE_HUD_ITEM) \
	X(MSAFE_DOOR_LOCK_STATE) \
	X(MSAFE_DOOR_ACTIVATE) \
	X(MSAFE_DOOR_STOP) \
	X(MSAFE_DOOR_POSITION) \
	X(MSAFE_TRIGGER_SET) \
	X(MSAFE_INVEN_ADD_OBJECT) \
	X(MSAFE_INVEN_REMOVE_OBJECT) \
	X(MSAFE_INVEN_ADD_TYPE_ID) \
	X(MSAFE_INVEN_REMOVE) \
	X(MSAFE_COUNTERMEASURE_REMOVE) \
	X(MSAFE_COUNTERMEASURE_ADD) \
	X(MSAFE_OBJECT_ROTDRAG) \
	X(MSAFE_OBJECT_TYPE) \
	X(MSAFE_OBJECT_ID) \
	X(MSAFE_OBJECT_CONTROL_TYPE) \
	X(MSAFE_OBJECT_FLAGS) \
	X(MSAFE_OBJECT_MOVEMENT_TYPE) \
	X(MSAFE_OBJECT_CREATION_TIME) \
	X(MSAFE_OBJECT_PHYSICS_FLAGS) \
	X(MSAFE_OBJECT_PARENT) \
	X(MSAFE_WEAPON_CHECK) \
	X(MSAFE_WEAPON_ADD)

#define DECLARE_MSAFE_CALLER(name) void TestCaller_##name(void);
MSAFE_CALLFUNCTION_TEST_CALLERS(DECLARE_MSAFE_CALLER)
#undef DECLARE_MSAFE_CALLER

void RunAllMSafeCallFunctionTestCallers(void);

#endif
