#ifndef TESTS_OSIRIS_EVENT_CALLERS_H
#define TESTS_OSIRIS_EVENT_CALLERS_H

#include "osiris_event_test.h"

#define OSIRIS_EVENT_TEST_CALLERS(X) \
	X(EVT_INTERVAL) \
	X(EVT_AI_FRAME) \
	X(EVT_DAMAGED) \
	X(EVT_COLLIDE) \
	X(EVT_CREATED) \
	X(EVT_DESTROY) \
	X(EVT_TIMER) \
	X(EVT_USE) \
	X(EVT_AI_NOTIFY) \
	X(EVT_AI_INIT) \
	X(EVT_CHANGESEG) \
	X(EVT_SAVESTATE) \
	X(EVT_RESTORESTATE) \
	X(EVT_MEMRESTORE) \
	X(EVT_TIMERCANCEL) \
	X(EVT_AIN_OBJKILLED) \
	X(EVT_AIN_SEEPLAYER) \
	X(EVT_AIN_WHITOBJECT) \
	X(EVT_AIN_GOALCOMPLETE) \
	X(EVT_AIN_GOALFAIL) \
	X(EVT_AIN_MELEE_HIT) \
	X(EVT_AIN_MELEE_ATTACK_FRAME) \
	X(EVT_AIN_MOVIE_START) \
	X(EVT_AIN_MOVIE_END) \
	X(EVT_MATCEN_CREATE) \
	X(EVT_DOOR_ACTIVATE) \
	X(EVT_DOOR_CLOSE) \
	X(EVT_CHILD_DIED) \
	X(EVT_LEVEL_GOAL_COMPLETE) \
	X(EVT_ALL_LEVEL_GOALS_COMPLETE) \
	X(EVT_LEVEL_GOAL_ITEM_COMPLETE) \
	X(EVT_PLAYER_MOVIE_START) \
	X(EVT_PLAYER_MOVIE_END) \
	X(EVT_PLAYER_RESPAWN) \
	X(EVT_PLAYER_DIES)

#define DECLARE_OSIRIS_EVENT_CALLER(name) void TestCaller_##name(void);
OSIRIS_EVENT_TEST_CALLERS(DECLARE_OSIRIS_EVENT_CALLER)
#undef DECLARE_OSIRIS_EVENT_CALLER

void RunAllOsirisEventTestCallers(void);

#endif
