#include "eventinfo.h"
#include "cfile_wrappers.h"

#include <stddef.h>
#include <string.h>

namespace emuabi
{
namespace
{
#define ABI_COPY_I32(name) dst.name = src.name;
#define ABI_COPY_U8(name) dst.name = src.name;
#define ABI_COPY_F32(name) dst.name = src.name;
#define ABI_COPY_PTR32(name) dst.name = vm.encode_ptr32(src.name);

#define ABI_DECL_I32(name) int32_t name;
#define ABI_DECL_U8(name) uint8_t name;
#define ABI_DECL_F32(name) float name;
#define ABI_DECL_PTR32(name) uint32_t name;

#define OSIRIS_EVTINTERVAL_FIELDS(APPLY) \
	APPLY(F32, frame_time) \
	APPLY(F32, game_time)

#define OSIRIS_EVTDAMAGED_FIELDS(APPLY) \
	APPLY(F32, damage) \
	APPLY(I32, it_handle) \
	APPLY(I32, weapon_handle) \
	APPLY(I32, damage_type)

#define OSIRIS_EVTCOLLIDE_FIELDS(APPLY) \
	APPLY(I32, it_handle)

#define OSIRIS_EVTDESTROY_FIELDS(APPLY) \
	APPLY(U8, is_dying)

#define OSIRIS_EVTTIMER_FIELDS(APPLY) \
	APPLY(I32, id) \
	APPLY(F32, game_time)

#define OSIRIS_EVTUSE_FIELDS(APPLY) \
	APPLY(I32, it_handle)

#define OSIRIS_EVTSAVESTATE_FIELDS(APPLY) \
	APPLY(PTR32, fileptr)

#define OSIRIS_EVTRESTORESTATE_FIELDS(APPLY) \
	APPLY(PTR32, fileptr)

#define OSIRIS_EVTAINOTIFY_FIELDS(APPLY) \
	APPLY(I32, notify_type) \
	APPLY(I32, it_handle) \
	APPLY(I32, goal_num) \
	APPLY(I32, goal_uid) \
	APPLY(I32, enabler_num)

#define OSIRIS_EVTCHANGESEG_FIELDS(APPLY) \
	APPLY(I32, room_num)

#define OSIRIS_EVTMEMRESTORE_FIELDS(APPLY) \
	APPLY(I32, id) \
	APPLY(PTR32, memory_ptr)

#define OSIRIS_EVTTIMERCANCEL_FIELDS(APPLY) \
	APPLY(I32, handle) \
	APPLY(U8, detonated)

#define OSIRIS_EVTCHILDDIED_FIELDS(APPLY) \
	APPLY(I32, it_handle)

#define OSIRIS_EVTMATCENCREATE_FIELDS(APPLY) \
	APPLY(I32, it_handle) \
	APPLY(I32, id)

#define OSIRIS_EVTLEVELGOALCOMPLETE_FIELDS(APPLY) \
	APPLY(I32, level_goal_index)

#define OSIRIS_EVTLEVELGOALITEMCOMPLETE_FIELDS(APPLY) \
	APPLY(I32, level_goal_index)

#define OSIRIS_EVTPLAYERRESPAWN_FIELDS(APPLY) \
	APPLY(I32, it_handle)

#define OSIRIS_EVTPLAYERDIES_FIELDS(APPLY) \
	APPLY(I32, it_handle)

#define DECLARE_32_STRUCT(native_type, generated_type, fields_macro) \
	struct generated_type \
	{ \
		fields_macro(DECLARE_32_STRUCT_FIELD) \
	};

#define DECLARE_32_STRUCT_FIELD(kind, name) ABI_DECL_##kind(name)

	DECLARE_32_STRUCT(tOSIRISEVTINTERVAL, tOSIRISEVTINTERVAL32, OSIRIS_EVTINTERVAL_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTDAMAGED, tOSIRISEVTDAMAGED32, OSIRIS_EVTDAMAGED_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTCOLLIDE, tOSIRISEVTCOLLIDE32, OSIRIS_EVTCOLLIDE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTDESTROY, tOSIRISEVTDESTROY32, OSIRIS_EVTDESTROY_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTTIMER, tOSIRISEVTTIMER32, OSIRIS_EVTTIMER_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTUSE, tOSIRISEVTUSE32, OSIRIS_EVTUSE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTSAVESTATE, tOSIRISEVTSAVESTATE32, OSIRIS_EVTSAVESTATE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTRESTORESTATE, tOSIRISEVTRESTORESTATE32, OSIRIS_EVTRESTORESTATE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTAINOTIFY, tOSIRISEVTAINOTIFY32, OSIRIS_EVTAINOTIFY_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTCHANGESEG, tOSIRISEVTCHANGESEG32, OSIRIS_EVTCHANGESEG_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTMEMRESTORE, tOSIRISEVTMEMRESTORE32, OSIRIS_EVTMEMRESTORE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTTIMERCANCEL, tOSIRISEVTTIMERCANCEL32, OSIRIS_EVTTIMERCANCEL_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTCHILDDIED, tOSIRISEVTCHILDDIED32, OSIRIS_EVTCHILDDIED_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTMATCENCREATE, tOSIRISEVTMATCENCREATE32, OSIRIS_EVTMATCENCREATE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTLEVELGOALCOMPLETE, tOSIRISEVTLEVELGOALCOMPLETE32, OSIRIS_EVTLEVELGOALCOMPLETE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTLEVELGOALITEMCOMPLETE, tOSIRISEVTLEVELGOALITEMCOMPLETE32, OSIRIS_EVTLEVELGOALITEMCOMPLETE_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTPLAYERRESPAWN, tOSIRISEVTPLAYERRESPAWN32, OSIRIS_EVTPLAYERRESPAWN_FIELDS)
	DECLARE_32_STRUCT(tOSIRISEVTPLAYERDIES, tOSIRISEVTPLAYERDIES32, OSIRIS_EVTPLAYERDIES_FIELDS)

#undef DECLARE_32_STRUCT_FIELD
#undef DECLARE_32_STRUCT

#if 0
	static_assert(sizeof(tOSIRISEVTINTERVAL32) == sizeof(tOSIRISEVTINTERVAL32), "Event interval ABI mismatch");
	static_assert(sizeof(tOSIRISEVTDAMAGED32) == sizeof(tOSIRISEVTDAMAGED32), "Event damaged ABI mismatch");
	static_assert(sizeof(tOSIRISEVTCOLLIDE32) == sizeof(tOSIRISEVTCOLLIDE32), "Event collide ABI mismatch");
	static_assert(sizeof(tOSIRISEVTDESTROY32) == sizeof(tOSIRISEVTDESTROY32), "Event destroy ABI mismatch");
	static_assert(sizeof(tOSIRISEVTTIMER32) == sizeof(tOSIRISEVTTIMER32), "Event timer ABI mismatch");
	static_assert(sizeof(tOSIRISEVTUSE32) == sizeof(tOSIRISEVTUSE32), "Event use ABI mismatch");
	static_assert(sizeof(tOSIRISEVTSAVESTATE32) == sizeof(tOSIRISEVTSAVESTATE32), "Event save-state ABI mismatch");
	static_assert(sizeof(tOSIRISEVTRESTORESTATE32) == sizeof(tOSIRISEVTRESTORESTATE32), "Event restore-state ABI mismatch");
	static_assert(sizeof(tOSIRISEVTAINOTIFY32) == sizeof(tOSIRISEVTAINOTIFY32), "Event AI notify ABI mismatch");
	static_assert(sizeof(tOSIRISEVTCHANGESEG32) == sizeof(tOSIRISEVTCHANGESEG32), "Event change-seg ABI mismatch");
	static_assert(sizeof(tOSIRISEVTMEMRESTORE32) == sizeof(tOSIRISEVTMEMRESTORE32), "Event mem-restore ABI mismatch");
	static_assert(sizeof(tOSIRISEVTTIMERCANCEL32) == sizeof(tOSIRISEVTTIMERCANCEL32), "Event timercancel ABI mismatch");
	static_assert(sizeof(tOSIRISEVTCHILDDIED32) == sizeof(tOSIRISEVTCHILDDIED32), "Event child-died ABI mismatch");
	static_assert(sizeof(tOSIRISEVTMATCENCREATE32) == sizeof(tOSIRISEVTMATCENCREATE32), "Event matcen-create ABI mismatch");
	static_assert(sizeof(tOSIRISEVTLEVELGOALCOMPLETE32) == sizeof(tOSIRISEVTLEVELGOALCOMPLETE32), "Event level-goal-complete ABI mismatch");
	static_assert(sizeof(tOSIRISEVTLEVELGOALITEMCOMPLETE32) == sizeof(tOSIRISEVTLEVELGOALITEMCOMPLETE32), "Event level-goal-item-complete ABI mismatch");
	static_assert(sizeof(tOSIRISEVTPLAYERRESPAWN32) == sizeof(tOSIRISEVTPLAYERRESPAWN32), "Event player-respawn ABI mismatch");
	static_assert(sizeof(tOSIRISEVTPLAYERDIES32) == sizeof(tOSIRISEVTPLAYERDIES32), "Event player-dies ABI mismatch");
#endif

#define DEFINE_ENCODER(native_type, generated_type, fields_macro) \
	void encode_##generated_type(const native_type& src, generated_type& dst, const VmPtrEncoder& vm) \
	{ \
		memset(&dst, 0, sizeof(dst)); \
		fields_macro(ENCODE_STRUCT_FIELD) \
	}

#define ENCODE_STRUCT_FIELD(kind, name) ABI_COPY_##kind(name)

	DEFINE_ENCODER(tOSIRISEVTINTERVAL, tOSIRISEVTINTERVAL32, OSIRIS_EVTINTERVAL_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTDAMAGED, tOSIRISEVTDAMAGED32, OSIRIS_EVTDAMAGED_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTCOLLIDE, tOSIRISEVTCOLLIDE32, OSIRIS_EVTCOLLIDE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTDESTROY, tOSIRISEVTDESTROY32, OSIRIS_EVTDESTROY_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTTIMER, tOSIRISEVTTIMER32, OSIRIS_EVTTIMER_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTUSE, tOSIRISEVTUSE32, OSIRIS_EVTUSE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTSAVESTATE, tOSIRISEVTSAVESTATE32, OSIRIS_EVTSAVESTATE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTRESTORESTATE, tOSIRISEVTRESTORESTATE32, OSIRIS_EVTRESTORESTATE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTAINOTIFY, tOSIRISEVTAINOTIFY32, OSIRIS_EVTAINOTIFY_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTCHANGESEG, tOSIRISEVTCHANGESEG32, OSIRIS_EVTCHANGESEG_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTMEMRESTORE, tOSIRISEVTMEMRESTORE32, OSIRIS_EVTMEMRESTORE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTTIMERCANCEL, tOSIRISEVTTIMERCANCEL32, OSIRIS_EVTTIMERCANCEL_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTCHILDDIED, tOSIRISEVTCHILDDIED32, OSIRIS_EVTCHILDDIED_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTMATCENCREATE, tOSIRISEVTMATCENCREATE32, OSIRIS_EVTMATCENCREATE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTLEVELGOALCOMPLETE, tOSIRISEVTLEVELGOALCOMPLETE32, OSIRIS_EVTLEVELGOALCOMPLETE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTLEVELGOALITEMCOMPLETE, tOSIRISEVTLEVELGOALITEMCOMPLETE32, OSIRIS_EVTLEVELGOALITEMCOMPLETE_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTPLAYERRESPAWN, tOSIRISEVTPLAYERRESPAWN32, OSIRIS_EVTPLAYERRESPAWN_FIELDS)
	DEFINE_ENCODER(tOSIRISEVTPLAYERDIES, tOSIRISEVTPLAYERDIES32, OSIRIS_EVTPLAYERDIES_FIELDS)

#undef ENCODE_STRUCT_FIELD
#undef DEFINE_ENCODER

#define DECODE_STRUCT_FIELD(kind, name) ABI_COPY_##kind(name)
#define DEFINE_DECODER(native_type, generated_type, fields_macro) \
	void decode_##generated_type(const generated_type& src, native_type& dst, const VmPtrDecoder& vm) \
	{ \
		memset(&dst, 0, sizeof(dst)); \
		fields_macro(DECODE_STRUCT_FIELD) \
	}

#if 0
	DEFINE_DECODER(tOSIRISEVTINTERVAL, tOSIRISEVTINTERVAL32, OSIRIS_EVTINTERVAL_FIELDS)
	DEFINE_DECODER(tOSIRISEVTDAMAGED, tOSIRISEVTDAMAGED32, OSIRIS_EVTDAMAGED_FIELDS)
	DEFINE_DECODER(tOSIRISEVTCOLLIDE, tOSIRISEVTCOLLIDE32, OSIRIS_EVTCOLLIDE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTDESTROY, tOSIRISEVTDESTROY32, OSIRIS_EVTDESTROY_FIELDS)
	DEFINE_DECODER(tOSIRISEVTTIMER, tOSIRISEVTTIMER32, OSIRIS_EVTTIMER_FIELDS)
	DEFINE_DECODER(tOSIRISEVTUSE, tOSIRISEVTUSE32, OSIRIS_EVTUSE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTSAVESTATE, tOSIRISEVTSAVESTATE32, OSIRIS_EVTSAVESTATE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTRESTORESTATE, tOSIRISEVTRESTORESTATE32, OSIRIS_EVTRESTORESTATE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTAINOTIFY, tOSIRISEVTAINOTIFY32, OSIRIS_EVTAINOTIFY_FIELDS)
	DEFINE_DECODER(tOSIRISEVTCHANGESEG, tOSIRISEVTCHANGESEG32, OSIRIS_EVTCHANGESEG_FIELDS)
	DEFINE_DECODER(tOSIRISEVTMEMRESTORE, tOSIRISEVTMEMRESTORE32, OSIRIS_EVTMEMRESTORE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTTIMERCANCEL, tOSIRISEVTTIMERCANCEL32, OSIRIS_EVTTIMERCANCEL_FIELDS)
	DEFINE_DECODER(tOSIRISEVTCHILDDIED, tOSIRISEVTCHILDDIED32, OSIRIS_EVTCHILDDIED_FIELDS)
	DEFINE_DECODER(tOSIRISEVTMATCENCREATE, tOSIRISEVTMATCENCREATE32, OSIRIS_EVTMATCENCREATE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTLEVELGOALCOMPLETE, tOSIRISEVTLEVELGOALCOMPLETE32, OSIRIS_EVTLEVELGOALCOMPLETE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTLEVELGOALITEMCOMPLETE, tOSIRISEVTLEVELGOALITEMCOMPLETE32, OSIRIS_EVTLEVELGOALITEMCOMPLETE_FIELDS)
	DEFINE_DECODER(tOSIRISEVTPLAYERRESPAWN, tOSIRISEVTPLAYERRESPAWN32, OSIRIS_EVTPLAYERRESPAWN_FIELDS)
	DEFINE_DECODER(tOSIRISEVTPLAYERDIES, tOSIRISEVTPLAYERDIES32, OSIRIS_EVTPLAYERDIES_FIELDS)
#endif

#undef DEFINE_DECODER
#undef DECODE_STRUCT_FIELD

	template <typename DstEvent32, typename SrcEvent64, typename GeneratedEvent32>
	void encode_union_event(DstEvent32& dst, const SrcEvent64& src, const VmPtrEncoder& vm, void (*encode_fn)(const SrcEvent64&, GeneratedEvent32&, const VmPtrEncoder&))
	{
		GeneratedEvent32 encoded;
		encode_fn(src, encoded, vm);
		memcpy(&dst, &encoded, sizeof(encoded));
	}

typedef struct {} tOSIRISEVTCREATED32;
typedef struct {} tOSIRISEVTAIFRAME32;
typedef struct {} tOSIRISEVTAIINIT32;
typedef struct {} tOSIRISEVTLEVELSTART32;
typedef struct {} tOSIRISEVTLEVELEND32;
typedef struct {} tOSIRISEVTDOORACTIVATE32;
typedef struct {} tOSIRISEVTDOORCLOSE32;
typedef struct {} tOSIRISEVTPLAYERMOVIESTART32;
typedef struct {} tOSIRISEVTPLAYERMOVIEEND32;
typedef struct{
	union{
		tOSIRISEVTINTERVAL32		evt_interval;
		tOSIRISEVTAIFRAME32		evt_ai_frame;
		tOSIRISEVTDAMAGED32		evt_damaged;
		tOSIRISEVTCOLLIDE32		evt_collide;
		tOSIRISEVTCREATED32		evt_created;
		tOSIRISEVTDESTROY32		evt_destroy;
		tOSIRISEVTTIMER32			evt_timer;
		tOSIRISEVTUSE32			evt_use;
		tOSIRISEVTAINOTIFY32		evt_ai_notify;
		tOSIRISEVTAINOTIFY32		evt_ain_objkilled;
		tOSIRISEVTAINOTIFY32		evt_ain_seeplayer;
		tOSIRISEVTAINOTIFY32		evt_ain_whitobject;
		tOSIRISEVTAINOTIFY32		evt_ain_goalcomplete;
		tOSIRISEVTAINOTIFY32		evt_ain_goalinvalid;
		tOSIRISEVTAINOTIFY32		evt_ain_goalfail;
		tOSIRISEVTAINOTIFY32		evt_ain_goalerror;
		tOSIRISEVTAINOTIFY32		evt_ain_goalforcedone;
		tOSIRISEVTAINOTIFY32		evt_ain_melee_hit;
		tOSIRISEVTAINOTIFY32		evt_ain_melee_attack_frame;
		tOSIRISEVTAINOTIFY32		evt_ain_movie_start;
		tOSIRISEVTAINOTIFY32		evt_ain_movie_end;		
		tOSIRISEVTAIINIT32		evt_ai_init;
		tOSIRISEVTLEVELSTART32	evt_levelstart;
		tOSIRISEVTLEVELEND32		evt_levelend;
		tOSIRISEVTCHANGESEG32		evt_changeseg;
		tOSIRISEVTSAVESTATE32		evt_savestate;
		tOSIRISEVTRESTORESTATE32	evt_restorestate;
		tOSIRISEVTMEMRESTORE32	evt_memrestore;
		tOSIRISEVTTIMERCANCEL32	evt_timercancel;
		tOSIRISEVTMATCENCREATE32	evt_matcen_create;
		tOSIRISEVTDOORACTIVATE32	evt_door_activate;
		tOSIRISEVTDOORCLOSE32		evt_door_close;
		tOSIRISEVTCHILDDIED32     evt_child_died;
		tOSIRISEVTLEVELGOALCOMPLETE32	evt_level_goal_complete;
		tOSIRISEVTALLLEVELGOALSCOMPLETE evt_all_level_goals_complete;
		tOSIRISEVTLEVELGOALITEMCOMPLETE32	evt_level_goal_item_complete;
		tOSIRISEVTPLAYERMOVIESTART32	evt_player_movie_start;
		tOSIRISEVTPLAYERMOVIEEND32	evt_player_movie_end;
		tOSIRISEVTPLAYERRESPAWN32		evt_player_respawn;
		tOSIRISEVTPLAYERDIES32		evt_player_dies;
	};

	ABI_DECL_I32(me_handle);
	ABI_DECL_PTR32(extra_info);
}tOSIRISEventInfo32;

#undef ABI_COPY_I32
#undef ABI_COPY_U8
#undef ABI_COPY_F32
#undef ABI_COPY_PTR32
#undef ABI_DECL_I32
#undef ABI_DECL_U8
#undef ABI_DECL_F32
#undef ABI_DECL_PTR32
#undef OSIRIS_EVTINTERVAL_FIELDS
#undef OSIRIS_EVTDAMAGED_FIELDS
#undef OSIRIS_EVTCOLLIDE_FIELDS
#undef OSIRIS_EVTDESTROY_FIELDS
#undef OSIRIS_EVTTIMER_FIELDS
#undef OSIRIS_EVTUSE_FIELDS
#undef OSIRIS_EVTSAVESTATE_FIELDS
#undef OSIRIS_EVTRESTORESTATE_FIELDS
#undef OSIRIS_EVTAINOTIFY_FIELDS
#undef OSIRIS_EVTCHANGESEG_FIELDS
#undef OSIRIS_EVTMEMRESTORE_FIELDS
#undef OSIRIS_EVTTIMERCANCEL_FIELDS
#undef OSIRIS_EVTCHILDDIED_FIELDS
#undef OSIRIS_EVTMATCENCREATE_FIELDS
#undef OSIRIS_EVTLEVELGOALCOMPLETE_FIELDS
#undef OSIRIS_EVTLEVELGOALITEMCOMPLETE_FIELDS
#undef OSIRIS_EVTPLAYERRESPAWN_FIELDS
#undef OSIRIS_EVTPLAYERDIES_FIELDS
}


static_assert(sizeof(tOSIRISEventInfo32) == event_info_size_32, "Event interval ABI size mismatch");

#if 0
void decode_event_info(int event, const void* srcbuf, tOSIRISEventInfo& dst, const VmPtrDecoder& vm)
{
	memset(&dst, 0, sizeof(dst));
	if (!srcbuf)
	{
		return;
	}

	const tOSIRISEventInfo32& src = *static_cast<const tOSIRISEventInfo32*>(srcbuf);
	dst.me_handle = src.me_handle;
	dst.extra_info = vm.decode_ptr32(src.extra_info);

	switch (event)
	{
	case EVT_INTERVAL:
		decode_tOSIRISEVTINTERVAL32(src.evt_interval, dst.evt_interval, vm);
		break;
	case EVT_AI_FRAME:
	case EVT_CREATED:
	case EVT_AI_INIT:
	case EVT_DOOR_ACTIVATE:
	case EVT_DOOR_CLOSE:
	case EVT_ALL_LEVEL_GOALS_COMPLETE:
	case EVT_PLAYER_MOVIE_START:
	case EVT_PLAYER_MOVIE_END:
		break;
	case EVT_DAMAGED:
		decode_tOSIRISEVTDAMAGED32(src.evt_damaged, dst.evt_damaged, vm);
		break;
	case EVT_COLLIDE:
		decode_tOSIRISEVTCOLLIDE32(src.evt_collide, dst.evt_collide, vm);
		break;
	case EVT_DESTROY:
		decode_tOSIRISEVTDESTROY32(src.evt_destroy, dst.evt_destroy, vm);
		break;
	case EVT_TIMER:
		decode_tOSIRISEVTTIMER32(src.evt_timer, dst.evt_timer, vm);
		break;
	case EVT_USE:
		decode_tOSIRISEVTUSE32(src.evt_use, dst.evt_use, vm);
		break;
	case EVT_AI_NOTIFY:
	case EVT_AIN_OBJKILLED:
	case EVT_AIN_SEEPLAYER:
	case EVT_AIN_WHITOBJECT:
	case EVT_AIN_GOALCOMPLETE:
	case EVT_AIN_GOALFAIL:
	case EVT_AIN_MELEE_HIT:
	case EVT_AIN_MELEE_ATTACK_FRAME:
	case EVT_AIN_MOVIE_START:
	case EVT_AIN_MOVIE_END:
		decode_tOSIRISEVTAINOTIFY32(src.evt_ai_notify, dst.evt_ai_notify, vm);
		break;
	case EVT_CHANGESEG:
		decode_tOSIRISEVTCHANGESEG32(src.evt_changeseg, dst.evt_changeseg, vm);
		break;
	case EVT_SAVESTATE:
		decode_tOSIRISEVTSAVESTATE32(src.evt_savestate, dst.evt_savestate, vm);
		dst.evt_savestate.fileptr = emuabi::resolve_file_handle(src.evt_savestate.fileptr);
		break;
	case EVT_RESTORESTATE:
		decode_tOSIRISEVTRESTORESTATE32(src.evt_restorestate, dst.evt_restorestate, vm);
		dst.evt_restorestate.fileptr = emuabi::resolve_file_handle(src.evt_restorestate.fileptr);
		break;
	case EVT_MEMRESTORE:
		decode_tOSIRISEVTMEMRESTORE32(src.evt_memrestore, dst.evt_memrestore, vm);
		break;
	case EVT_TIMERCANCEL:
		decode_tOSIRISEVTTIMERCANCEL32(src.evt_timercancel, dst.evt_timercancel, vm);
		break;
	case EVT_CHILD_DIED:
		decode_tOSIRISEVTCHILDDIED32(src.evt_child_died, dst.evt_child_died, vm);
		break;
	case EVT_MATCEN_CREATE:
		decode_tOSIRISEVTMATCENCREATE32(src.evt_matcen_create, dst.evt_matcen_create, vm);
		break;
	case EVT_LEVEL_GOAL_COMPLETE:
		decode_tOSIRISEVTLEVELGOALCOMPLETE32(src.evt_level_goal_complete, dst.evt_level_goal_complete, vm);
		break;
	case EVT_LEVEL_GOAL_ITEM_COMPLETE:
		decode_tOSIRISEVTLEVELGOALITEMCOMPLETE32(src.evt_level_goal_item_complete, dst.evt_level_goal_item_complete, vm);
		break;
	case EVT_PLAYER_RESPAWN:
		decode_tOSIRISEVTPLAYERRESPAWN32(src.evt_player_respawn, dst.evt_player_respawn, vm);
		break;
	case EVT_PLAYER_DIES:
		decode_tOSIRISEVTPLAYERDIES32(src.evt_player_dies, dst.evt_player_dies, vm);
		break;
	default:
		break;
	}
}
#endif

void encode_event_info(int event, const tOSIRISEventInfo& src, void *dstbuf, const VmPtrEncoder& vm)
{
	tOSIRISEventInfo32 dst;
	memset(&dst, 0, sizeof(dst));
	dst.me_handle = src.me_handle;
	dst.extra_info = vm.encode_ptr32(src.extra_info);

	switch (event)
	{
	case EVT_INTERVAL:
		encode_union_event<tOSIRISEVTINTERVAL32, tOSIRISEVTINTERVAL, tOSIRISEVTINTERVAL32>(dst.evt_interval, src.evt_interval, vm, encode_tOSIRISEVTINTERVAL32);
		break;
	case EVT_AI_FRAME:
	case EVT_CREATED:
	case EVT_AI_INIT:
	case EVT_DOOR_ACTIVATE:
	case EVT_DOOR_CLOSE:
	case EVT_ALL_LEVEL_GOALS_COMPLETE:
	case EVT_PLAYER_MOVIE_START:
	case EVT_PLAYER_MOVIE_END:
		break;
	case EVT_DAMAGED:
		encode_union_event<tOSIRISEVTDAMAGED32, tOSIRISEVTDAMAGED, tOSIRISEVTDAMAGED32>(dst.evt_damaged, src.evt_damaged, vm, encode_tOSIRISEVTDAMAGED32);
		break;
	case EVT_COLLIDE:
		encode_union_event<tOSIRISEVTCOLLIDE32, tOSIRISEVTCOLLIDE, tOSIRISEVTCOLLIDE32>(dst.evt_collide, src.evt_collide, vm, encode_tOSIRISEVTCOLLIDE32);
		break;
	case EVT_DESTROY:
		encode_union_event<tOSIRISEVTDESTROY32, tOSIRISEVTDESTROY, tOSIRISEVTDESTROY32>(dst.evt_destroy, src.evt_destroy, vm, encode_tOSIRISEVTDESTROY32);
		break;
	case EVT_TIMER:
		encode_union_event<tOSIRISEVTTIMER32, tOSIRISEVTTIMER, tOSIRISEVTTIMER32>(dst.evt_timer, src.evt_timer, vm, encode_tOSIRISEVTTIMER32);
		break;
	case EVT_USE:
		encode_union_event<tOSIRISEVTUSE32, tOSIRISEVTUSE, tOSIRISEVTUSE32>(dst.evt_use, src.evt_use, vm, encode_tOSIRISEVTUSE32);
		break;
	case EVT_AI_NOTIFY:
	case EVT_AIN_OBJKILLED:
	case EVT_AIN_SEEPLAYER:
	case EVT_AIN_WHITOBJECT:
	case EVT_AIN_GOALCOMPLETE:
	case EVT_AIN_GOALFAIL:
	case EVT_AIN_MELEE_HIT:
	case EVT_AIN_MELEE_ATTACK_FRAME:
	case EVT_AIN_MOVIE_START:
	case EVT_AIN_MOVIE_END:
		encode_union_event<tOSIRISEVTAINOTIFY32, tOSIRISEVTAINOTIFY, tOSIRISEVTAINOTIFY32>(dst.evt_ai_notify, src.evt_ai_notify, vm, encode_tOSIRISEVTAINOTIFY32);
		break;
	case EVT_CHANGESEG:
		encode_union_event<tOSIRISEVTCHANGESEG32, tOSIRISEVTCHANGESEG, tOSIRISEVTCHANGESEG32>(dst.evt_changeseg, src.evt_changeseg, vm, encode_tOSIRISEVTCHANGESEG32);
		break;
	case EVT_SAVESTATE:
		encode_union_event<tOSIRISEVTSAVESTATE32, tOSIRISEVTSAVESTATE, tOSIRISEVTSAVESTATE32>(dst.evt_savestate, src.evt_savestate, vm, encode_tOSIRISEVTSAVESTATE32);
		break;
	case EVT_RESTORESTATE:
		encode_union_event<tOSIRISEVTRESTORESTATE32, tOSIRISEVTRESTORESTATE, tOSIRISEVTRESTORESTATE32>(dst.evt_restorestate, src.evt_restorestate, vm, encode_tOSIRISEVTRESTORESTATE32);
		break;
	case EVT_MEMRESTORE:
		encode_union_event<tOSIRISEVTMEMRESTORE32, tOSIRISEVTMEMRESTORE, tOSIRISEVTMEMRESTORE32>(dst.evt_memrestore, src.evt_memrestore, vm, encode_tOSIRISEVTMEMRESTORE32);
		break;
	case EVT_TIMERCANCEL:
		encode_union_event<tOSIRISEVTTIMERCANCEL32, tOSIRISEVTTIMERCANCEL, tOSIRISEVTTIMERCANCEL32>(dst.evt_timercancel, src.evt_timercancel, vm, encode_tOSIRISEVTTIMERCANCEL32);
		break;
	case EVT_CHILD_DIED:
		encode_union_event<tOSIRISEVTCHILDDIED32, tOSIRISEVTCHILDDIED, tOSIRISEVTCHILDDIED32>(dst.evt_child_died, src.evt_child_died, vm, encode_tOSIRISEVTCHILDDIED32);
		break;
	case EVT_MATCEN_CREATE:
		encode_union_event<tOSIRISEVTMATCENCREATE32, tOSIRISEVTMATCENCREATE, tOSIRISEVTMATCENCREATE32>(dst.evt_matcen_create, src.evt_matcen_create, vm, encode_tOSIRISEVTMATCENCREATE32);
		break;
	case EVT_LEVEL_GOAL_COMPLETE:
		encode_union_event<tOSIRISEVTLEVELGOALCOMPLETE32, tOSIRISEVTLEVELGOALCOMPLETE, tOSIRISEVTLEVELGOALCOMPLETE32>(dst.evt_level_goal_complete, src.evt_level_goal_complete, vm, encode_tOSIRISEVTLEVELGOALCOMPLETE32);
		break;
	case EVT_LEVEL_GOAL_ITEM_COMPLETE:
		encode_union_event<tOSIRISEVTLEVELGOALITEMCOMPLETE32, tOSIRISEVTLEVELGOALITEMCOMPLETE, tOSIRISEVTLEVELGOALITEMCOMPLETE32>(dst.evt_level_goal_item_complete, src.evt_level_goal_item_complete, vm, encode_tOSIRISEVTLEVELGOALITEMCOMPLETE32);
		break;
	case EVT_PLAYER_RESPAWN:
		encode_union_event<tOSIRISEVTPLAYERRESPAWN32, tOSIRISEVTPLAYERRESPAWN, tOSIRISEVTPLAYERRESPAWN32>(dst.evt_player_respawn, src.evt_player_respawn, vm, encode_tOSIRISEVTPLAYERRESPAWN32);
		break;
	case EVT_PLAYER_DIES:
		encode_union_event<tOSIRISEVTPLAYERDIES32, tOSIRISEVTPLAYERDIES, tOSIRISEVTPLAYERDIES32>(dst.evt_player_dies, src.evt_player_dies, vm, encode_tOSIRISEVTPLAYERDIES32);
		break;
	default:
		break;
	}
	memcpy(dstbuf, &dst, sizeof(dst));
}

void encode_event_info_with_file_handle(int event, const tOSIRISEventInfo& src, void *dstbuf, const VmPtrEncoder& vm, uint32_t file_handle)
{
	tOSIRISEventInfo adjusted = src;
	if (event == EVT_SAVESTATE)
		adjusted.evt_savestate.fileptr = 0;
	else if (event == EVT_RESTORESTATE)
		adjusted.evt_restorestate.fileptr = 0;

	encode_event_info(event, adjusted, dstbuf, vm);

	if (!dstbuf)
		return;

	tOSIRISEventInfo32& dst = *reinterpret_cast<tOSIRISEventInfo32*>(dstbuf);
	switch (event)
	{
	case EVT_SAVESTATE:
		dst.evt_savestate.fileptr = file_handle;
		break;
	case EVT_RESTORESTATE:
		dst.evt_restorestate.fileptr = file_handle;
		break;
	default:
		break;
	}
}

}
