#include "msafe.h"

#include <string.h>

namespace emuabi
{
namespace
{
#define ABI_COPY_I32(name) dst.name = src.name;
#define ABI_COPY_U32(name) dst.name = src.name;
#define ABI_COPY_I16(name) dst.name = src.name;
#define ABI_COPY_U16(name) dst.name = src.name;
#define ABI_COPY_I8(name) dst.name = src.name;
#define ABI_COPY_U8(name) dst.name = src.name;
#define ABI_COPY_F32(name) dst.name = src.name;
#define ABI_COPY_PTR32(name) dst.name = vm.decode_ptr32(src.name);
#define ABI_COPY_VECTOR(name) decode_vector(dst.name, src.name);
#define ABI_COPY_MATRIX(name) decode_matrix(dst.name, src.name);
#define ABI_COPY_CHAR_ARRAY(name, size) memcpy(dst.name, src.name, size);

#define ABI_DECL_I32(name) int32_t name;
#define ABI_DECL_U32(name) uint32_t name;
#define ABI_DECL_I16(name) int16_t name;
#define ABI_DECL_U16(name) uint16_t name;
#define ABI_DECL_I8(name) int8_t name;
#define ABI_DECL_U8(name) uint8_t name;
#define ABI_DECL_F32(name) float name;
#define ABI_DECL_PTR32(name) uint32_t name;
#define ABI_DECL_VECTOR(name) vector32 name;
#define ABI_DECL_MATRIX(name) matrix32 name;
#define ABI_DECL_CHAR_ARRAY(name, size) char name[size];

	struct vector32
	{
		float x;
		float y;
		float z;
	};

	struct matrix32
	{
		vector32 rvec;
		vector32 uvec;
		vector32 fvec;
	};

	static void decode_vector(vector& dst, const vector32& src)
	{
		dst.x = src.x;
		dst.y = src.y;
		dst.z = src.z;
	}

	static void decode_matrix(matrix& dst, const matrix32& src)
	{
		decode_vector(dst.rvec, src.rvec);
		decode_vector(dst.uvec, src.uvec);
		decode_vector(dst.fvec, src.fvec);
	}

#define MSAFE_STRUCT_FIELDS(APPLY) \
	APPLY(I32, roomnum) \
	APPLY(I16, facenum) \
	APPLY(I16, texnum) \
	APPLY(I16, portalnum) \
	APPLY(F32, fog_r) \
	APPLY(F32, fog_g) \
	APPLY(F32, fog_b) \
	APPLY(F32, fog_depth) \
	APPLY(VECTOR, wind) \
	APPLY(U8, pulse_time) \
	APPLY(U8, pulse_offset) \
	APPLY(U32, objhandle) \
	APPLY(U32, ithandle) \
	APPLY(F32, shields) \
	APPLY(F32, energy) \
	APPLY(I16, start_tick) \
	APPLY(I16, end_tick) \
	APPLY(F32, cycle_time) \
	APPLY(I32, type) \
	APPLY(I32, id) \
	APPLY(I32, aux_type) \
	APPLY(I32, aux_id) \
	APPLY(U32, checksum) \
	APPLY(I32, path_id) \
	APPLY(F32, amount) \
	APPLY(U8, damage_type) \
	APPLY(U32, killer_handle) \
	APPLY(F32, ammo) \
	APPLY(U8, playsound) \
	APPLY(U8, remove) \
	APPLY(U8, do_powerup) \
	APPLY(VECTOR, velocity) \
	APPLY(VECTOR, rot_velocity) \
	APPLY(F32, rot_drag) \
	APPLY(VECTOR, thrust) \
	APPLY(VECTOR, rot_thrust) \
	APPLY(I8, control_type) \
	APPLY(I8, movement_type) \
	APPLY(F32, creation_time) \
	APPLY(I32, physics_flags) \
	APPLY(VECTOR, pos) \
	APPLY(MATRIX, orient) \
	APPLY(F32, anim_frame) \
	APPLY(U8, is_real) \
	APPLY(U8, random) \
	APPLY(U8, unused2) \
	APPLY(I8, gunpoint) \
	APPLY(U8, effect_type) \
	APPLY(U8, phys_info) \
	APPLY(F32, drag) \
	APPLY(F32, mass) \
	APPLY(U16, unused) \
	APPLY(I32, randval) \
	APPLY(U8, trigger_num) \
	APPLY(I32, sound_handle) \
	APPLY(F32, volume) \
	APPLY(I32, index) \
	APPLY(F32, scalar) \
	APPLY(F32, interval) \
	APPLY(U8, state) \
	APPLY(I8, slot) \
	APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH) \
	APPLY(CHAR_ARRAY, name, MSAFE_NAME_LENGTH) \
	APPLY(I32, color) \
	APPLY(F32, longevity) \
	APPLY(F32, lifetime) \
	APPLY(F32, size) \
	APPLY(F32, speed) \
	APPLY(I32, count) \
	APPLY(I32, flags) \
	APPLY(PTR32, list) \
	APPLY(U32, control_mask) \
	APPLY(U8, control_val) \
	APPLY(F32, light_distance) \
	APPLY(F32, r1) \
	APPLY(F32, g1) \
	APPLY(F32, b1) \
	APPLY(F32, r2) \
	APPLY(F32, g2) \
	APPLY(F32, b2) \
	APPLY(F32, time_interval) \
	APPLY(F32, flicker_distance) \
	APPLY(F32, directional_dot) \
	APPLY(I32, timebits) \
	APPLY(VECTOR, pos2) \
	APPLY(CHAR_ARRAY, message2, MSAFE_MESSAGE_LENGTH)

#define MSAFE_FIELDS_NONE(APPLY)
#define MSAFE_FIELDS_STATE_SCALAR(APPLY) APPLY(U8, state) APPLY(F32, scalar)
#define MSAFE_FIELDS_WEATHER_LIGHTNING(APPLY) MSAFE_FIELDS_STATE_SCALAR(APPLY) APPLY(I32, randval)
#define MSAFE_FIELDS_WEATHER_LIGHTNING_BOLT(APPLY) \
	APPLY(I16, texnum) APPLY(I32, flags) APPLY(U32, objhandle) APPLY(U32, ithandle) APPLY(I32, roomnum) \
	APPLY(VECTOR, pos) APPLY(VECTOR, pos2) APPLY(F32, lifetime) APPLY(I32, color) APPLY(F32, size) \
	APPLY(U8, state) APPLY(I32, count) APPLY(F32, interval) APPLY(I32, index) APPLY(F32, g1) APPLY(F32, g2)
#define MSAFE_FIELDS_ROOM_TEXTURE(APPLY) APPLY(I32, roomnum) APPLY(I16, facenum) APPLY(I32, index)
#define MSAFE_FIELDS_ROOM_WIND(APPLY) APPLY(I32, roomnum) APPLY(VECTOR, wind)
#define MSAFE_FIELDS_ROOM_FOG(APPLY) APPLY(I32, roomnum) APPLY(F32, fog_r) APPLY(F32, fog_g) APPLY(F32, fog_b) APPLY(F32, fog_depth)
#define MSAFE_FIELDS_ROOM_STATE(APPLY) APPLY(I32, roomnum) APPLY(U8, state)
#define MSAFE_FIELDS_ROOM_LIGHT_PULSE(APPLY) APPLY(I32, roomnum) APPLY(U8, pulse_time) APPLY(U8, pulse_offset)
#define MSAFE_FIELDS_ROOM_CHANGING_FOG(APPLY) MSAFE_FIELDS_ROOM_FOG(APPLY) APPLY(F32, interval)
#define MSAFE_FIELDS_ROOM_CHANGING_WIND(APPLY) MSAFE_FIELDS_ROOM_WIND(APPLY) APPLY(F32, interval)
#define MSAFE_FIELDS_ROOM_PORTAL_RENDER(APPLY) APPLY(I32, roomnum) APPLY(I16, portalnum) APPLY(U8, state) APPLY(I32, flags)
#define MSAFE_FIELDS_ROOM_PORTAL_BLOCK(APPLY) APPLY(I32, roomnum) APPLY(I16, portalnum) APPLY(U8, state)
#define MSAFE_FIELDS_ROOM_BREAK_GLASS(APPLY) APPLY(I32, roomnum) APPLY(I16, portalnum)
#define MSAFE_FIELDS_ROOM_DAMAGE(APPLY) APPLY(I32, roomnum) APPLY(F32, amount) APPLY(I32, index)
#define MSAFE_FIELDS_ROOMNUM(APPLY) APPLY(I32, roomnum)
#define MSAFE_FIELDS_OBJECT_FIRE_WEAPON(APPLY) APPLY(U32, objhandle) APPLY(I32, index) APPLY(I8, gunpoint)
#define MSAFE_FIELDS_OBJECT_SETONFIRE(APPLY) APPLY(U32, objhandle) APPLY(F32, longevity) APPLY(F32, interval) APPLY(U32, ithandle)
#define MSAFE_FIELDS_OBJECT_SHIELDS(APPLY) APPLY(U32, objhandle) APPLY(F32, shields)
#define MSAFE_FIELDS_OBJECT_ENERGY(APPLY) APPLY(U32, objhandle) APPLY(F32, energy)
#define MSAFE_FIELDS_OBJECT_HANDLE_STATE(APPLY) APPLY(U32, objhandle) APPLY(U8, state)
#define MSAFE_FIELDS_OBJECT_PLAYER_CMASK(APPLY) APPLY(U32, objhandle) APPLY(U32, control_mask) APPLY(U8, control_val)
#define MSAFE_FIELDS_OBJECT_PLAYER_KEY(APPLY) APPLY(U32, ithandle) APPLY(I32, index) APPLY(U32, objhandle) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH)
#define MSAFE_FIELDS_OBJECT_HANDLE_SCALAR(APPLY) APPLY(U32, objhandle) APPLY(F32, scalar)
#define MSAFE_FIELDS_OBJECT_ADD_WEAPON(APPLY) APPLY(U32, objhandle) APPLY(I32, index) APPLY(F32, ammo)
#define MSAFE_FIELDS_OBJECT_DAMAGE_OBJECT(APPLY) APPLY(U32, objhandle) APPLY(U32, killer_handle) APPLY(U8, damage_type) APPLY(F32, amount)
#define MSAFE_FIELDS_OBJECT_START_SPEW(APPLY) \
	APPLY(U32, objhandle) APPLY(I8, gunpoint) APPLY(U8, random) APPLY(U8, is_real) APPLY(U8, effect_type) APPLY(U8, phys_info) \
	APPLY(F32, drag) APPLY(F32, mass) APPLY(F32, interval) APPLY(F32, longevity) APPLY(F32, lifetime) APPLY(F32, size) APPLY(F32, speed) APPLY(I32, id)
#define MSAFE_FIELDS_OBJECT_STOP_SPEW(APPLY) APPLY(I32, id)
#define MSAFE_FIELDS_OBJECT_HANDLE(APPLY) APPLY(U32, objhandle)
#define MSAFE_FIELDS_OBJECT_REMOVE(APPLY) APPLY(U32, objhandle) APPLY(U8, playsound)
#define MSAFE_FIELDS_OBJECT_HANDLE_STATE_LIFETIME(APPLY) APPLY(U32, objhandle) APPLY(U8, state) APPLY(F32, lifetime)
#define MSAFE_FIELDS_STATE_LIFETIME(APPLY) APPLY(U8, state) APPLY(F32, lifetime)
#define MSAFE_FIELDS_OBJECT_LIGHT_DIST(APPLY) APPLY(U32, objhandle) APPLY(F32, light_distance)
#define MSAFE_FIELDS_OBJECT_LIGHT_COLOR(APPLY) APPLY(U32, objhandle) APPLY(F32, r1) APPLY(F32, g1) APPLY(F32, b1)
#define MSAFE_FIELDS_OBJECT_AMOUNT_LIFETIME(APPLY) APPLY(U32, objhandle) APPLY(F32, amount) APPLY(F32, lifetime)
#define MSAFE_FIELDS_AMOUNT(APPLY) APPLY(F32, amount)
#define MSAFE_FIELDS_OBJECT_SHAKE_AREA(APPLY) APPLY(U32, objhandle) APPLY(F32, scalar) APPLY(F32, amount)
#define MSAFE_FIELDS_OBJECT_WORLD_POSITION(APPLY) APPLY(U32, objhandle) APPLY(I32, roomnum) APPLY(VECTOR, pos) APPLY(MATRIX, orient)
#define MSAFE_FIELDS_OBJECT_PLAYER_CONTROLAI(APPLY) APPLY(I8, slot) APPLY(U8, state)
#define MSAFE_FIELDS_OBJECT_DESTROY_ROBOTS_EXCEPT(APPLY) APPLY(PTR32, list) APPLY(I32, count)
#define MSAFE_FIELDS_SOUND_STREAMING(APPLY) APPLY(U8, state) APPLY(U32, objhandle) APPLY(CHAR_ARRAY, name, MSAFE_NAME_LENGTH) APPLY(F32, volume) APPLY(I32, flags) APPLY(I32, sound_handle) APPLY(I8, slot)
#define MSAFE_FIELDS_SOUND_2D(APPLY) APPLY(U8, state) APPLY(U32, objhandle) APPLY(I32, index) APPLY(F32, volume) APPLY(I32, sound_handle) APPLY(I8, slot)
#define MSAFE_FIELDS_SOUND_OBJECT(APPLY) APPLY(U32, objhandle) APPLY(I32, index) APPLY(I32, sound_handle)
#define MSAFE_FIELDS_SOUND_VOLUME_OBJ(APPLY) APPLY(U32, objhandle) APPLY(F32, volume)
#define MSAFE_FIELDS_MUSIC_REGION(APPLY) APPLY(U8, state) APPLY(U32, objhandle) APPLY(I32, index) APPLY(I8, slot)
#define MSAFE_FIELDS_MISC_LEVELGOAL(APPLY) APPLY(I32, index) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH) APPLY(I32, type) APPLY(I32, count)
#define MSAFE_FIELDS_INDEX(APPLY) APPLY(I32, index)
#define MSAFE_FIELDS_MISC_ENABLE_SHIP(APPLY) APPLY(CHAR_ARRAY, name, MSAFE_NAME_LENGTH) APPLY(U8, state)
#define MSAFE_FIELDS_MISC_HUD_MESSAGE(APPLY) APPLY(U8, state) APPLY(U32, objhandle) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH) APPLY(I32, color) APPLY(I8, slot)
#define MSAFE_FIELDS_MISC_GAME_MESSAGE(APPLY) APPLY(U8, state) APPLY(U32, objhandle) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH) APPLY(CHAR_ARRAY, message2, MSAFE_MESSAGE_LENGTH) APPLY(I32, color) APPLY(I8, slot)
#define MSAFE_FIELDS_MISC_END_LEVEL(APPLY) APPLY(U8, state)
#define MSAFE_FIELDS_MISC_POPUP_CAMERA(APPLY) APPLY(U32, objhandle) APPLY(F32, interval) APPLY(F32, scalar) APPLY(I8, gunpoint)
#define MSAFE_FIELDS_MISC_GUIDEBOT_NAME(APPLY) APPLY(U32, objhandle) APPLY(CHAR_ARRAY, name, MSAFE_NAME_LENGTH)
#define MSAFE_FIELDS_MISC_START_TIMER(APPLY) APPLY(I32, index) APPLY(I32, color)
#define MSAFE_FIELDS_MISC_UPDATE_HUD_ITEM(APPLY) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH) APPLY(I32, color)
#define MSAFE_FIELDS_DOOR_POSITION(APPLY) APPLY(U32, objhandle) APPLY(F32, scalar)
#define MSAFE_FIELDS_TRIGGER_SET(APPLY) APPLY(U8, trigger_num) APPLY(U8, state)
#define MSAFE_FIELDS_INVEN_ADD_OBJECT(APPLY) APPLY(U32, objhandle) APPLY(U32, ithandle) APPLY(I32, flags) APPLY(CHAR_ARRAY, message, MSAFE_MESSAGE_LENGTH)
#define MSAFE_FIELDS_INVEN_REMOVE_OBJECT(APPLY) APPLY(U32, objhandle) APPLY(U32, ithandle)
#define MSAFE_FIELDS_INVEN_ADD_TYPE_ID(APPLY) APPLY(U32, objhandle) APPLY(I32, type) APPLY(I32, id) APPLY(I32, flags)
#define MSAFE_FIELDS_HANDLE_TYPE_ID(APPLY) APPLY(U32, objhandle) APPLY(I32, type) APPLY(I32, id)
#define MSAFE_FIELDS_COUNTERMEASURE_ADD(APPLY) APPLY(U32, objhandle) APPLY(I32, count) APPLY(CHAR_ARRAY, name, MSAFE_NAME_LENGTH) APPLY(I32, aux_type) APPLY(I32, aux_id)
#define MSAFE_FIELDS_OBJECT_ROTDRAG(APPLY) APPLY(U32, objhandle) APPLY(F32, rot_drag)
#define MSAFE_FIELDS_OBJECT_TYPE(APPLY) APPLY(U32, objhandle) APPLY(I32, type)
#define MSAFE_FIELDS_OBJECT_ID(APPLY) APPLY(U32, objhandle) APPLY(I32, id)
#define MSAFE_FIELDS_OBJECT_CONTROL_TYPE(APPLY) APPLY(U32, objhandle) APPLY(I8, control_type)
#define MSAFE_FIELDS_OBJECT_FLAGS(APPLY) APPLY(U32, objhandle) APPLY(I32, flags)
#define MSAFE_FIELDS_OBJECT_MOVEMENT_TYPE(APPLY) APPLY(U32, objhandle) APPLY(I8, movement_type)
#define MSAFE_FIELDS_OBJECT_CREATION_TIME(APPLY) APPLY(U32, objhandle) APPLY(F32, creation_time)
#define MSAFE_FIELDS_OBJECT_PHYSICS_FLAGS(APPLY) APPLY(U32, objhandle) APPLY(I32, physics_flags)
#define MSAFE_FIELDS_OBJECT_PARENT(APPLY) APPLY(U32, objhandle) APPLY(U32, ithandle)
#define MSAFE_FIELDS_WEAPON_ADD(APPLY) APPLY(U32, objhandle) APPLY(I32, index) APPLY(U8, state) APPLY(I32, count)

#define DECLARE_32_STRUCT_FIELD(kind, ...) ABI_DECL_##kind(__VA_ARGS__)
	struct msafe_struct32
	{
		MSAFE_STRUCT_FIELDS(DECLARE_32_STRUCT_FIELD)
	};
#undef DECLARE_32_STRUCT_FIELD

#define DECODE_STRUCT_FIELD(kind, ...) ABI_COPY_##kind(__VA_ARGS__)
#define DECODE_CASE(type_value, fields_macro) \
	case type_value: \
		fields_macro(DECODE_STRUCT_FIELD) \
		break

	static void decode_msafe_fields(int type, const msafe_struct32& src, msafe_struct& dst, const VmPtrDecoder& vm)
	{
		switch (type)
		{
		DECODE_CASE(MSAFE_WEATHER_RAIN, MSAFE_FIELDS_STATE_SCALAR);
		DECODE_CASE(MSAFE_WEATHER_SNOW, MSAFE_FIELDS_STATE_SCALAR);
		DECODE_CASE(MSAFE_WEATHER_LIGHTNING, MSAFE_FIELDS_WEATHER_LIGHTNING);
		DECODE_CASE(MSAFE_WEATHER_LIGHTNING_BOLT, MSAFE_FIELDS_WEATHER_LIGHTNING_BOLT);
		DECODE_CASE(MSAFE_ROOM_TEXTURE, MSAFE_FIELDS_ROOM_TEXTURE);
		DECODE_CASE(MSAFE_ROOM_WIND, MSAFE_FIELDS_ROOM_WIND);
		DECODE_CASE(MSAFE_ROOM_FOG, MSAFE_FIELDS_ROOM_FOG);
		DECODE_CASE(MSAFE_ROOM_FOG_STATE, MSAFE_FIELDS_ROOM_STATE);
		DECODE_CASE(MSAFE_ROOM_LIGHT_PULSE, MSAFE_FIELDS_ROOM_LIGHT_PULSE);
		DECODE_CASE(MSAFE_ROOM_LIGHT_FLICKER, MSAFE_FIELDS_ROOM_STATE);
		DECODE_CASE(MSAFE_ROOM_LIGHT_STROBE, MSAFE_FIELDS_ROOM_STATE);
		DECODE_CASE(MSAFE_ROOM_REFUEL, MSAFE_FIELDS_ROOM_STATE);
		DECODE_CASE(MSAFE_ROOM_CHANGING_FOG, MSAFE_FIELDS_ROOM_CHANGING_FOG);
		DECODE_CASE(MSAFE_ROOM_CHANGING_WIND, MSAFE_FIELDS_ROOM_CHANGING_WIND);
		DECODE_CASE(MSAFE_ROOM_PORTAL_RENDER, MSAFE_FIELDS_ROOM_PORTAL_RENDER);
		DECODE_CASE(MSAFE_ROOM_PORTAL_BLOCK, MSAFE_FIELDS_ROOM_PORTAL_BLOCK);
		DECODE_CASE(MSAFE_ROOM_BREAK_GLASS, MSAFE_FIELDS_ROOM_BREAK_GLASS);
		DECODE_CASE(MSAFE_ROOM_DAMAGE, MSAFE_FIELDS_ROOM_DAMAGE);
		DECODE_CASE(MSAFE_ROOM_REMOVE_ALL_POWERUPS, MSAFE_FIELDS_ROOMNUM);
		DECODE_CASE(MSAFE_OBJECT_FIRE_WEAPON, MSAFE_FIELDS_OBJECT_FIRE_WEAPON);
		DECODE_CASE(MSAFE_OBJECT_SETONFIRE, MSAFE_FIELDS_OBJECT_SETONFIRE);
		DECODE_CASE(MSAFE_OBJECT_SHIELDS, MSAFE_FIELDS_OBJECT_SHIELDS);
		DECODE_CASE(MSAFE_OBJECT_ENERGY, MSAFE_FIELDS_OBJECT_ENERGY);
		DECODE_CASE(MSAFE_SHOW_ENABLED_CONTROLS, MSAFE_FIELDS_OBJECT_HANDLE_STATE);
		DECODE_CASE(MSAFE_OBJECT_PLAYER_CMASK, MSAFE_FIELDS_OBJECT_PLAYER_CMASK);
		DECODE_CASE(MSAFE_OBJECT_PLAYER_KEY, MSAFE_FIELDS_OBJECT_PLAYER_KEY);
		DECODE_CASE(MSAFE_OBJECT_MOVEMENT_SCALAR, MSAFE_FIELDS_OBJECT_HANDLE_SCALAR);
		DECODE_CASE(MSAFE_OBJECT_RECHARGE_SCALAR, MSAFE_FIELDS_OBJECT_HANDLE_SCALAR);
		DECODE_CASE(MSAFE_OBJECT_WSPEED_SCALAR, MSAFE_FIELDS_OBJECT_HANDLE_SCALAR);
		DECODE_CASE(MSAFE_OBJECT_ARMOR_SCALAR, MSAFE_FIELDS_OBJECT_HANDLE_SCALAR);
		DECODE_CASE(MSAFE_OBJECT_DAMAGE_SCALAR, MSAFE_FIELDS_OBJECT_HANDLE_SCALAR);
		DECODE_CASE(MSAFE_OBJECT_ADD_WEAPON, MSAFE_FIELDS_OBJECT_ADD_WEAPON);
		DECODE_CASE(MSAFE_OBJECT_DAMAGE_OBJECT, MSAFE_FIELDS_OBJECT_DAMAGE_OBJECT);
		DECODE_CASE(MSAFE_OBJECT_START_SPEW, MSAFE_FIELDS_OBJECT_START_SPEW);
		DECODE_CASE(MSAFE_OBJECT_STOP_SPEW, MSAFE_FIELDS_OBJECT_STOP_SPEW);
		DECODE_CASE(MSAFE_OBJECT_NO_RENDER, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_OBJECT_GHOST, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_OBJECT_UNGHOST, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_OBJECT_REMOVE, MSAFE_FIELDS_OBJECT_REMOVE);
		DECODE_CASE(MSAFE_OBJECT_INVULNERABLE, MSAFE_FIELDS_OBJECT_HANDLE_STATE_LIFETIME);
		DECODE_CASE(MSAFE_OBJECT_CLOAKALLPLAYERS, MSAFE_FIELDS_STATE_LIFETIME);
		DECODE_CASE(MSAFE_OBJECT_CLOAK, MSAFE_FIELDS_OBJECT_HANDLE_STATE_LIFETIME);
		DECODE_CASE(MSAFE_OBJECT_LIGHT_DIST, MSAFE_FIELDS_OBJECT_LIGHT_DIST);
		DECODE_CASE(MSAFE_OBJECT_LIGHT_COLOR, MSAFE_FIELDS_OBJECT_LIGHT_COLOR);
		DECODE_CASE(MSAFE_OBJECT_DEFORM, MSAFE_FIELDS_OBJECT_AMOUNT_LIFETIME);
		DECODE_CASE(MSAFE_OBJECT_SPARKS, MSAFE_FIELDS_OBJECT_AMOUNT_LIFETIME);
		DECODE_CASE(MSAFE_OBJECT_VIEWER_SHAKE, MSAFE_FIELDS_AMOUNT);
		DECODE_CASE(MSAFE_OBJECT_SHAKE_AREA, MSAFE_FIELDS_OBJECT_SHAKE_AREA);
		DECODE_CASE(MSAFE_OBJECT_WORLD_POSITION, MSAFE_FIELDS_OBJECT_WORLD_POSITION);
		DECODE_CASE(MSAFE_OBJECT_PLAYER_CONTROLAI, MSAFE_FIELDS_OBJECT_PLAYER_CONTROLAI);
		DECODE_CASE(MSAFE_OBJECT_DESTROY_ROBOTS_EXCEPT, MSAFE_FIELDS_OBJECT_DESTROY_ROBOTS_EXCEPT);
		DECODE_CASE(MSAFE_SOUND_STREAMING, MSAFE_FIELDS_SOUND_STREAMING);
		DECODE_CASE(MSAFE_SOUND_2D, MSAFE_FIELDS_SOUND_2D);
		DECODE_CASE(MSAFE_SOUND_OBJECT, MSAFE_FIELDS_SOUND_OBJECT);
		DECODE_CASE(MSAFE_SOUND_STOP, MSAFE_FIELDS_NONE);
		DECODE_CASE(MSAFE_SOUND_STOP_OBJ, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_SOUND_VOLUME_OBJ, MSAFE_FIELDS_SOUND_VOLUME_OBJ);
		DECODE_CASE(MSAFE_MUSIC_REGION, MSAFE_FIELDS_MUSIC_REGION);
		DECODE_CASE(MSAFE_MISC_LEVELGOAL, MSAFE_FIELDS_MISC_LEVELGOAL);
		DECODE_CASE(MSAFE_MISC_WAYPOINT, MSAFE_FIELDS_INDEX);
		DECODE_CASE(MSAFE_MISC_ENABLE_SHIP, MSAFE_FIELDS_MISC_ENABLE_SHIP);
		DECODE_CASE(MSAFE_MISC_FILTERED_HUD_MESSAGE, MSAFE_FIELDS_MISC_HUD_MESSAGE);
		DECODE_CASE(MSAFE_MISC_HUD_MESSAGE, MSAFE_FIELDS_MISC_HUD_MESSAGE);
		DECODE_CASE(MSAFE_MISC_GAME_MESSAGE, MSAFE_FIELDS_MISC_GAME_MESSAGE);
		DECODE_CASE(MSAFE_MISC_END_LEVEL, MSAFE_FIELDS_MISC_END_LEVEL);
		DECODE_CASE(MSAFE_MISC_POPUP_CAMERA, MSAFE_FIELDS_MISC_POPUP_CAMERA);
		DECODE_CASE(MSAFE_MISC_CLOSE_POPUP, MSAFE_FIELDS_NONE);
		DECODE_CASE(MSAFE_MISC_GUIDEBOT_NAME, MSAFE_FIELDS_MISC_GUIDEBOT_NAME);
		DECODE_CASE(MSAFE_MISC_START_TIMER, MSAFE_FIELDS_MISC_START_TIMER);
		DECODE_CASE(MSAFE_MISC_UPDATE_HUD_ITEM, MSAFE_FIELDS_MISC_UPDATE_HUD_ITEM);
		DECODE_CASE(MSAFE_DOOR_LOCK_STATE, MSAFE_FIELDS_OBJECT_HANDLE_STATE);
		DECODE_CASE(MSAFE_DOOR_ACTIVATE, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_DOOR_STOP, MSAFE_FIELDS_OBJECT_HANDLE);
		DECODE_CASE(MSAFE_DOOR_POSITION, MSAFE_FIELDS_DOOR_POSITION);
		DECODE_CASE(MSAFE_TRIGGER_SET, MSAFE_FIELDS_TRIGGER_SET);
		DECODE_CASE(MSAFE_INVEN_ADD_OBJECT, MSAFE_FIELDS_INVEN_ADD_OBJECT);
		DECODE_CASE(MSAFE_INVEN_REMOVE_OBJECT, MSAFE_FIELDS_INVEN_REMOVE_OBJECT);
		DECODE_CASE(MSAFE_INVEN_ADD_TYPE_ID, MSAFE_FIELDS_INVEN_ADD_TYPE_ID);
		DECODE_CASE(MSAFE_INVEN_REMOVE, MSAFE_FIELDS_HANDLE_TYPE_ID);
		DECODE_CASE(MSAFE_COUNTERMEASURE_REMOVE, MSAFE_FIELDS_HANDLE_TYPE_ID);
		DECODE_CASE(MSAFE_COUNTERMEASURE_ADD, MSAFE_FIELDS_COUNTERMEASURE_ADD);
		DECODE_CASE(MSAFE_OBJECT_ROTDRAG, MSAFE_FIELDS_OBJECT_ROTDRAG);
		DECODE_CASE(MSAFE_OBJECT_TYPE, MSAFE_FIELDS_OBJECT_TYPE);
		DECODE_CASE(MSAFE_OBJECT_ID, MSAFE_FIELDS_OBJECT_ID);
		DECODE_CASE(MSAFE_OBJECT_CONTROL_TYPE, MSAFE_FIELDS_OBJECT_CONTROL_TYPE);
		DECODE_CASE(MSAFE_OBJECT_FLAGS, MSAFE_FIELDS_OBJECT_FLAGS);
		DECODE_CASE(MSAFE_OBJECT_MOVEMENT_TYPE, MSAFE_FIELDS_OBJECT_MOVEMENT_TYPE);
		DECODE_CASE(MSAFE_OBJECT_CREATION_TIME, MSAFE_FIELDS_OBJECT_CREATION_TIME);
		DECODE_CASE(MSAFE_OBJECT_PHYSICS_FLAGS, MSAFE_FIELDS_OBJECT_PHYSICS_FLAGS);
		DECODE_CASE(MSAFE_OBJECT_PARENT, MSAFE_FIELDS_OBJECT_PARENT);
		DECODE_CASE(MSAFE_WEAPON_CHECK, MSAFE_FIELDS_NONE);
		DECODE_CASE(MSAFE_WEAPON_ADD, MSAFE_FIELDS_WEAPON_ADD);
		default:
			break;
		}
	}

#undef DECODE_CASE
#undef DECODE_STRUCT_FIELD
#undef MSAFE_FIELDS_NONE
#undef MSAFE_FIELDS_STATE_SCALAR
#undef MSAFE_FIELDS_WEATHER_LIGHTNING
#undef MSAFE_FIELDS_WEATHER_LIGHTNING_BOLT
#undef MSAFE_FIELDS_ROOM_TEXTURE
#undef MSAFE_FIELDS_ROOM_WIND
#undef MSAFE_FIELDS_ROOM_FOG
#undef MSAFE_FIELDS_ROOM_STATE
#undef MSAFE_FIELDS_ROOM_LIGHT_PULSE
#undef MSAFE_FIELDS_ROOM_CHANGING_FOG
#undef MSAFE_FIELDS_ROOM_CHANGING_WIND
#undef MSAFE_FIELDS_ROOM_PORTAL_RENDER
#undef MSAFE_FIELDS_ROOM_PORTAL_BLOCK
#undef MSAFE_FIELDS_ROOM_BREAK_GLASS
#undef MSAFE_FIELDS_ROOM_DAMAGE
#undef MSAFE_FIELDS_ROOMNUM
#undef MSAFE_FIELDS_OBJECT_FIRE_WEAPON
#undef MSAFE_FIELDS_OBJECT_SETONFIRE
#undef MSAFE_FIELDS_OBJECT_SHIELDS
#undef MSAFE_FIELDS_OBJECT_ENERGY
#undef MSAFE_FIELDS_OBJECT_HANDLE_STATE
#undef MSAFE_FIELDS_OBJECT_PLAYER_CMASK
#undef MSAFE_FIELDS_OBJECT_PLAYER_KEY
#undef MSAFE_FIELDS_OBJECT_HANDLE_SCALAR
#undef MSAFE_FIELDS_OBJECT_ADD_WEAPON
#undef MSAFE_FIELDS_OBJECT_DAMAGE_OBJECT
#undef MSAFE_FIELDS_OBJECT_START_SPEW
#undef MSAFE_FIELDS_OBJECT_STOP_SPEW
#undef MSAFE_FIELDS_OBJECT_HANDLE
#undef MSAFE_FIELDS_OBJECT_REMOVE
#undef MSAFE_FIELDS_OBJECT_HANDLE_STATE_LIFETIME
#undef MSAFE_FIELDS_STATE_LIFETIME
#undef MSAFE_FIELDS_OBJECT_LIGHT_DIST
#undef MSAFE_FIELDS_OBJECT_LIGHT_COLOR
#undef MSAFE_FIELDS_OBJECT_AMOUNT_LIFETIME
#undef MSAFE_FIELDS_AMOUNT
#undef MSAFE_FIELDS_OBJECT_SHAKE_AREA
#undef MSAFE_FIELDS_OBJECT_WORLD_POSITION
#undef MSAFE_FIELDS_OBJECT_PLAYER_CONTROLAI
#undef MSAFE_FIELDS_OBJECT_DESTROY_ROBOTS_EXCEPT
#undef MSAFE_FIELDS_SOUND_STREAMING
#undef MSAFE_FIELDS_SOUND_2D
#undef MSAFE_FIELDS_SOUND_OBJECT
#undef MSAFE_FIELDS_SOUND_VOLUME_OBJ
#undef MSAFE_FIELDS_MUSIC_REGION
#undef MSAFE_FIELDS_MISC_LEVELGOAL
#undef MSAFE_FIELDS_INDEX
#undef MSAFE_FIELDS_MISC_ENABLE_SHIP
#undef MSAFE_FIELDS_MISC_HUD_MESSAGE
#undef MSAFE_FIELDS_MISC_GAME_MESSAGE
#undef MSAFE_FIELDS_MISC_END_LEVEL
#undef MSAFE_FIELDS_MISC_POPUP_CAMERA
#undef MSAFE_FIELDS_MISC_GUIDEBOT_NAME
#undef MSAFE_FIELDS_MISC_START_TIMER
#undef MSAFE_FIELDS_MISC_UPDATE_HUD_ITEM
#undef MSAFE_FIELDS_DOOR_POSITION
#undef MSAFE_FIELDS_TRIGGER_SET
#undef MSAFE_FIELDS_INVEN_ADD_OBJECT
#undef MSAFE_FIELDS_INVEN_REMOVE_OBJECT
#undef MSAFE_FIELDS_INVEN_ADD_TYPE_ID
#undef MSAFE_FIELDS_HANDLE_TYPE_ID
#undef MSAFE_FIELDS_COUNTERMEASURE_ADD
#undef MSAFE_FIELDS_OBJECT_ROTDRAG
#undef MSAFE_FIELDS_OBJECT_TYPE
#undef MSAFE_FIELDS_OBJECT_ID
#undef MSAFE_FIELDS_OBJECT_CONTROL_TYPE
#undef MSAFE_FIELDS_OBJECT_FLAGS
#undef MSAFE_FIELDS_OBJECT_MOVEMENT_TYPE
#undef MSAFE_FIELDS_OBJECT_CREATION_TIME
#undef MSAFE_FIELDS_OBJECT_PHYSICS_FLAGS
#undef MSAFE_FIELDS_OBJECT_PARENT
#undef MSAFE_FIELDS_WEAPON_ADD
#undef MSAFE_STRUCT_FIELDS
#undef ABI_COPY_I32
#undef ABI_COPY_U32
#undef ABI_COPY_I16
#undef ABI_COPY_U16
#undef ABI_COPY_I8
#undef ABI_COPY_U8
#undef ABI_COPY_F32
#undef ABI_COPY_PTR32
#undef ABI_COPY_VECTOR
#undef ABI_COPY_MATRIX
#undef ABI_COPY_CHAR_ARRAY
#undef ABI_DECL_I32
#undef ABI_DECL_U32
#undef ABI_DECL_I16
#undef ABI_DECL_U16
#undef ABI_DECL_I8
#undef ABI_DECL_U8
#undef ABI_DECL_F32
#undef ABI_DECL_PTR32
#undef ABI_DECL_VECTOR
#undef ABI_DECL_MATRIX
#undef ABI_DECL_CHAR_ARRAY
}

void decode_msafe_struct(int type, const void* srcbuf, msafe_struct& dst, const VmPtrDecoder& vm)
{
	memset(&dst, 0, sizeof(dst));
	if (!srcbuf)
	{
		return;
	}

	const msafe_struct32& src = *static_cast<const msafe_struct32*>(srcbuf);
	decode_msafe_fields(type, src, dst, vm);
}
}
